import os, time, sys
from Plugins.Configs.Settings import *

def Apps():
    clearConsole()
    #Banner
    Index_Banner()

    print(Bright_Red +"Cryptic Hats Hackers Organizations")
    print("Use This Apps To Change Members Phone, To")
    print("Keep Members Busy With Cool Games, To learn")
    print("Programming Offline And Online Plus So On!")
    print(Bright_Magenta +"Lists OF All Apps")

    #Recommanded Apps
    print(Bright_Blue + "[" + Bright_Red + "]" + Bright_Magenta + "->" + Bright_Yellow + "Recommanded Apps")
    
    print(Bright_Magenta + Ms1 + Bright_Green +"). Alison Courses")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Study IT and Get Certificate For Free.")
    print(Bright_Magenta + Ms2 + Bright_Green +"). Code Editor")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Code In Their Android Smart Phones.")
    print(Bright_Magenta + Ms3 + Bright_Green +"). F-Droid")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Install The Best Termux Version That Works.")
    print(Bright_Magenta + Ms4 + Bright_Green +"). GitHub")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Get Source Codes And Packages Installations Instructions.")
    print(Bright_Magenta + Ms5 + Bright_Green +"). HA Tunnel Plus")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Access DFN.hat Files And Access Free Internet.")
    print(Bright_Magenta + Ms6 + Bright_Green +"). ProtonMail")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Have An Encrypted Email Address.")
    print(Bright_Magenta + Ms7 + Bright_Green +"). ProtonVPN")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Change Their Country Location And IP-Address.")
    print(Bright_Magenta + Ms8 + Bright_Green +"). T-UI")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Change Their Android OS To Terminal OS.")
    print(Bright_Magenta + Ms9 + Bright_Green +"). Telegram")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Stay Updated And Be Able To Download The Org Files.")
    print(Bright_Magenta + Ms10 + Bright_Green +"). Termux")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Access Our BlackDocument And Upcoming Hacking Tools.")
    print(Bright_Magenta + Ms11 + Bright_Green +"). Termux T_C")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Get More Termux Tools Installation Instructions.")
    print(Bright_Magenta + Ms12 + Bright_Green +"). Udemy")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Study IT and Get Certificate For Free.")
    print(Bright_Magenta + Ms13 + Bright_Green +"). Yaaic")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Connect To The Organization Server.")
    Loading_Prograss()

    #Learning Apps
    print(Bright_Blue + "[" + Bright_Red + "]" + Bright_Magenta + "->" + Bright_Yellow + "Learning Apps")
    print(Bright_Magenta + Ms1 + Bright_Green +"). Advanced Networking")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("About Networking And Uses Advanced Education.")
    print(Bright_Magenta + Ms2 + Bright_Green +"). Alison Courses")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("IT and Get Certificate For Free.")
    print(Bright_Magenta + Ms3 + Bright_Green +"). AWD - IDE For Web Dev")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Web Developing And Is A Full Stock App.")
    print(Bright_Magenta + Ms4 + Bright_Green +"). CMD Command List")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("To USe Command Prompt Like A Pro.")
    print(Bright_Magenta + Ms5 + Bright_Green +"). Codepoint Learn PHP")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("PHP Web Developing.")
    print(Bright_Magenta + Ms6 + Bright_Green +"). HTML & CSS Basics")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Basics About HTML And CSS Langauages.")
    print(Bright_Magenta + Ms7 + Bright_Green +"). HTML CSS PHP Frameworks")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Full Stock In Web Developing.")
    print(Bright_Magenta + Ms8 + Bright_Green +"). Learn JAVAScript Offline")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Javascript Language In A Simple Way.")
    print(Bright_Magenta + Ms9 + Bright_Green +"). Learn PHP Offline")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("PHP Programming Language In A Simple Way.")
    print(Bright_Magenta + Ms10 + Bright_Green +"). Linux Command Library")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Linux Terminal And Have Also Advanced Commands.")
    print(Bright_Magenta + Ms11 + Bright_Green +"). Termux T_C")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Assist Memebers")
    print("To Get More Termux Tools Installation Instructions.")
    print(Bright_Magenta + Ms12 + Bright_Green +"). PyThon For Beginners-Offline Tutorial")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Python Language In A Simple Way For Beginners.")
    print(Bright_Magenta + Ms13 + Bright_Green +"). Python X")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("Python With An Online App.")
    Loading_Prograss()

    #IT Games
    print(Bright_Blue + "[" + Bright_Red + "]" + Bright_Magenta + "->" + Bright_Yellow + "IT Games")
    print(Bright_Magenta + Ms1 + Bright_Green +"). HackBot")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Keep Memebers")
    print("Entertained All Times.")
    print(Bright_Magenta + Ms2 + Bright_Green +"). Hacker")
    print(Bright_Red + "Description; "+ Bright_Green + "This App keep Memebers")
    print("Entertained All Times.")
    print(Bright_Magenta + Ms3 + Bright_Green +"). Hacker Game")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Keep Memebers")
    print("Entertained All Times.")
    print(Bright_Magenta + Ms4 + Bright_Green +"). Hack Ex")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Keep Memebers")
    print("Entertained All Times.")
    print(Bright_Magenta + Ms5 + Bright_Green +"). Hacking Hero")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Keep Memebers")
    print("Entertained All Times.")
    print(Bright_Magenta + Ms6 + Bright_Green +"). I Hacker" + Bright_Red + " Recommanded")
    print(Bright_Red + "Description; "+ Bright_Green + "This App Teach Memebers")
    print("How To Crack Passwords From 'Basics' To 'GrandMaster' Level.")
    Loading_Prograss()